name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Download dependencies
      run: npm i
    - name: Lint
      run: npm run lint
    - name: Unit Test
      run: npm run test
